#!/bin/sh

# Libraries will be installed to /usr/local/lib, binaries to
# /usr/local/bin.  If libraries could not be found; perhaps
#'/usr/local/lib' is missing in #/etc/ld.so.conf.

ln -s src/ptk/x11/* src/ptk/
libtoolize
aclocal
automake --add-missing
autoconf
./configure --disable-static
make
echo You may now \'make install\'.
